name: Test and Deploy Nodejs Backend Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      USERNAME: ${{ secrets.USERNAME }}
      KEY: ${{ secrets.KEY }}
      PORT: ${{ secrets.PORT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2   # Set up Node.js env't
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install              # Install all dependencies

      

      - name: Ssh and Deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            debug: true
            script: |
                cd /home/monitor/nodejsapp
                git pull origin main
                npm install --production
                npm install --production
                sudo systemctl restart nodejsapp.service
    
          
            
        
